### ISSUE TITLE
How to: Same Global Azure online event co-organized by two communities

### ISSUE THREAD

**Issue by icebeam7** [globalazure/communities#153]
Hello, I have a question. 

I understand that each community should do a separate PR in order to appear in the map/website. 

We'd like to co-organize the same online event, should we include the Sessionize info separately as well, or only one of the communities do it in the PR? 

Can you enlighten me, please? :)

**Comment by noopman** [comment]
Hello! Does it work to register as two separate "locations" in the data.json file? That will appear as two different events for your community. I maybe don't understand fully your situation, sorry if I misunderstood.

**Comment by icebeam7** [comment]
Hello @noopman thank you for your response and sorry for the confusion. 

There are two communities that will co-operate and co-organize the Global Azure event. I just want to check: if we use the same Sessionize ID...

Community 1 JSON file:
`"CommunityInfo": {
    "Name": "Comunidad Xamarin en Español",
    "SessionizeApiId": "a3vb1g"
}`

Community 2 JSON file:
`"CommunityInfo": {
    "Name": "Community 2",
    "SessionizeApiId": "a3vb1g"
}
`

would that make sessions to be duplicated on the global website?

Do you prefer that only one community registers the `SessionizeApiId`? The other one will be blank. 

Thank you for your insight.

**Comment by noopman** [comment]
Ah... That is a very good question. Try to register both and let's see if they would show up double! ;) Haha, no better not do that. I BET they will show up double. Issue is one of your communities would look like it has no sessions online, and the other would have all of them. That is a shame. Let's ask @davidjrh who knows the most about this integration, but I think that would be the case.

**Comment by davidjrh** [comment]
Hi @icebeam7, you can just use one file and add two different locations in the json file. Check https://github.com/globalazure/communities/tree/main/2023/globalazurespain as reference. This a co-organized event in Spain (Madrid, Barcelona and Zaragoza) with a single Sessionize event. Let me know if you have any additional question.

**Comment by icebeam7** [comment]
Hello @davidjrh, great thank you, that works for us! I'll follow your recommendation and will come back if I have any other questions.

Have a great day and thank you @noopman for the valuable help!
