### ISSUE TITLE
Sessionize details not correctly setup for GlobalAzureNMK location

### ISSUE THREAD

**Issue by davidjrh** [globalazure/communities#194]
Hi @glazuremk @darkomilevski

Our agenda integration process is throwing a warning telling us that your Sessionize endpoint hasn't been configured correctly, is returning HTML/javascript instead of JSON. Please, review the Sessionize API endpoint configuration and make sure is setup for JSON as mentioned on the instructions available at https://blog.globalazure.net/Blog/Post/301/Sessionize-integration-setup-for-local-event-organizers-for-2023-edition

https://sessionize.com/api/v2/49j2iij7/view/Sessions

**Comment by davidjrh** [comment]
Hi @glazuremk @darkomilevski can you check this? I'm still seeing HTML/Javascript at https://sessionize.com/api/v2/49j2iij7/view/Sessions

**Comment by glazuremk** [comment]
Hi @davidjrh , I think I updated the SessionizeApiId field in data.json to use following ApiId = zv07f3vq

I jus checked data.json on github and there is "SessionizeApiId": "zv07f3vq",

**Comment by davidjrh** [comment]
Super! Just checked and everything looks good! Thanks
