### ISSUE TITLE
Sessionize details not correctly setup for KMUG location

### ISSUE THREAD

**Issue by davidjrh** [globalazure/communities#195]
Hi @anuraj

Our agenda integration process is throwing a warning telling us that your Sessionize endpoint hasn't been configured correctly, is returning HTML/javascript instead of JSON. Please, review the Sessionize API endpoint configuration and make sure is setup for JSON as mentioned on the instructions available at https://blog.globalazure.net/Blog/Post/301/Sessionize-integration-setup-for-local-event-organizers-for-2023-edition

https://sessionize.com/api/v2/rvb4n87f/view/Sessions

**Comment by anuraj** [comment]
Hi @davidjrh 

Let me check and will update it.

**Comment by anuraj** [comment]
Hi @davidjrh It is done. It was the format issue. It was selected as HTML and now I changed it to JSON.

**Comment by noopman** [comment]
Perfect, thanks!
