### ISSUE TITLE
Sessionize details not correctly setup for MicrosoftReactorLondon location

### ISSUE THREAD

**Issue by davidjrh** [globalazure/communities#196]
Hi @callumbwhyte @poornimanayar

Our agenda integration process is throwing a warning telling us that your Sessionize endpoint hasn't been configured correctly, is returning HTML/javascript instead of JSON. Please, review the Sessionize API endpoint configuration and make sure is setup for JSON as mentioned on the instructions available at https://blog.globalazure.net/Blog/Post/301/Sessionize-integration-setup-for-local-event-organizers-for-2023-edition

https://sessionize.com/api/v2/gnrmj8fs/view/Sessions

**Comment by callumbwhyte** [comment]
Hey @davidjrh,

Thanks for pointing that out... I believe that's now fixed! We haven't confirmed any sessions just yet so the feed is empty.

Cheers,
Callum

**Comment by noopman** [comment]
Perfect!
