### ISSUE TITLE
Sessionize details not correctly setup for azugfrlocation

### ISSUE THREAD

**Issue by davidjrh** [globalazure/communities#198]
Hi @zecloud @IhorLeontiev @lecampusazure @CedricLeblond

Our agenda integration process is throwing a warning telling us that your Sessionize endpoint hasn't been configured correctly, is returning HTML/javascript instead of JSON. Please, review the Sessionize API endpoint configuration and make sure is setup for JSON as mentioned on the instructions available at https://blog.globalazure.net/Blog/Post/301/Sessionize-integration-setup-for-local-event-organizers-for-2023-edition

https://sessionize.com/api/v2/d0xh9rvj/view/Sessions

**Comment by zecloud** [comment]
Yes i confirm we're still building it :)

**Comment by davidjrh** [comment]
Hi @zecloud, the dates appear empty on the json, can you double check?

**Comment by CedricLeblond** [comment]
Hi David,
We needed to change the status "announce" to "true" . After the "startsat"
and "endsat" were set on the sessionize API for our event.

Le lun. 1 mai 2023 à 19:35, David Rodríguez ***@***.***> a
écrit :

**Comment by davidjrh** [comment]
Thanks! Looks good now!
