### ISSUE TITLE
Sessionize details not correctly setup for AucklandAzure location

### ISSUE THREAD

**Issue by davidjrh** [globalazure/communities#201]
Hi @marcelmedina @rbrayb

Seems there is a Sessionize configuration issue in your API endpoint. While the response format is in valid JSON format, the datetimes from the sessions (startsAt and endsAt) are not correctly populated, so the sessions appear in the global agenda as "Hidden" as they ocurred in the past (null date). Can you review your endpoint settings following the instructions provided at https://blog.globalazure.net/Blog/Post/301/Sessionize-integration-setup-for-local-event-organizers-for-2023-edition ?

https://sessionize.com/api/v2/ndvzcmoc/view/Sessions

**Comment by marcelmedina** [comment]
Thanks for pointing that out @davidjrh . We are still sorting the sessions.

**Comment by davidjrh** [comment]
Hello @marcelmedina the sessions are still missing the event date. Can you review that?

**Comment by davidjrh** [comment]
OK, this looks good! closing the issue
