### ISSUE TITLE
Add support for Twitter cards

### ISSUE THREAD

**Issue by StefanIvemo** [globalazure/communities#45]
I would like to see support for Twitter cards for the Global Azure site. It really helps highlighting the tweets to the community. What do you think? Can we add some metadata?

Right now it looks like this when I Tweet with a link to the site: https://twitter.com/StefanIvemo/status/1509867584719671299

**Comment by noopman** [comment]
That is a great idea that we haven't gotten 'round to. In fact we have the same issue on LinkedIn too!

**Comment by StefanIvemo** [comment]
Looks like this has ben resolved, right @noopman?

**Comment by davidjrh** [comment]
Yes! Implemented some weeks ago!
